### ISSUE TITLE
Suggested reference

### ISSUE THREAD

**Issue by mfenner** [sagepublishing/rejected_article_tracker_pkg#10]
Highly recommend to include (and discuss in `State of the Field`) this reference: 

Dominika Tkaczyk. „Reference Matching: For Real This Time“. Website. Crossref. Zugegriffen 9. Juli 2021. https://www.crossref.org/blog/reference-matching-for-real-this-time/.

openjournals/joss-reviews#3348

**Comment by ad48** [comment]
I've added this reference and pushed the changes.

**Comment by mfenner** [comment]
Thank you.
