### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by mfenner** [sagepublishing/rejected_article_tracker_pkg#12]
Example usage is described in the readme, but a dedicated example file would make this easier.

openjournals/joss-reviews#3348

**Comment by ad48** [comment]
Yes, I think we can do this. Just to check I've understood correctly, do you mean for us to create a file (e.g. JSON or xlsx) with the expected input so that users can run a test with it?

**Comment by mfenner** [comment]
Yes, exactly.

**Comment by ad48** [comment]
quick update: I'm working on this, but I thought it might be better to make it executable from the command line, so it means adding a bit more code.

**Comment by ad48** [comment]
I've added the file now as well as a simple `run_sample.py` file which processes it and produces an output file.

**Comment by danielskatz** [comment]
So can we close this issue now?  @mfenner? (who might be on vacation this week)

**Comment by mfenner** [comment]
Yes.
