### ISSUE TITLE
Discuss external dependencies

### ISSUE THREAD

**Issue by mfenner** [sagepublishing/rejected_article_tracker_pkg#13]
A stronger discussion of ScholarOne as external dependency would be helpful. It is a very popular journal submission system, but more guidance for users of other submission systems would be helpful.

This could for example be done by giving one or more examples (in particular name formatting) in the section `Article format`.

openjournals/joss-reviews#3348

**Comment by ad48** [comment]
Thank you for your comment. I've updated the `readme.md` to this effect.

**Comment by mfenner** [comment]
Thank you.
