### ISSUE TITLE
CI build is failing: missing tqdm

### ISSUE THREAD

**Issue by dhimmel** [sagepublishing/rejected_article_tracker_pkg#4]
https://github.com/sagepublishing/rejected_article_tracker_pkg/runs/2785999220#step:5:22

```python-traceback
ERROR: rejected_article_tracker (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: rejected_article_tracker
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/rejected_article_tracker_pkg/rejected_article_tracker_pkg/rejected_article_tracker/__init__.py", line 11, in <module>
    from .src.ML.ArXivOAIPMH import ArXivOAIPMH
  File "/home/runner/work/rejected_article_tracker_pkg/rejected_article_tracker_pkg/rejected_article_tracker/src/ML/ArXivOAIPMH.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by ad48** [comment]
Thanks for pointing this out. tqdm is present in setup.py now. I think that resolves the issue.

**Comment by danielskatz** [comment]
in https://github.com/openjournals/joss-reviews/issues/3348

**Comment by dhimmel** [comment]
> tqdm is present in setup.py now

Ah I do see https://github.com/sagepublishing/rejected_article_tracker_pkg/commit/bc2efec008c2c6fbf9d5d08a3f7926701ed74d26 that added tqdm, but this seems to have predated this issue.

I'm not sure why fc4f72de7b12c4acc6af597d61464ef7ed6e943b has that CI failure then. Anyways looking through the commit history, it looks like CI has been failing for a long time. CI on main should be passing.

**Comment by dhimmel** [comment]
Ah I do I know why. The dependencies are defined in two places: `requirements.txt` and `setup.py`. `requirements.txt` is used by CI and is missing `tqdm`:

https://github.com/sagepublishing/rejected_article_tracker_pkg/blob/fc4f72de7b12c4acc6af597d61464ef7ed6e943b/requirements.txt#L1-L10

Would probably be best to single-source your dependencies, although Python is not great at that. Noting https://packaging.python.org/discussions/install-requires-vs-requirements/. Is there any reason you need `requirements.txt`? Could probably just get by with `install_requires`?

**Comment by dhimmel** [comment]
While the general convention is that maintainers close issues, for the issues related to my openjournals/joss-reviews#3348 review, should I close my own issues? This will make it so we can use issue open/close status as an indicator of my satisfaction regarding a specific point?

**Comment by danielskatz** [comment]
either way is fine - you can always reopen the issue or open a new one if @ad48 closes something you disagree with

**Comment by ad48** [comment]
Apologies - I may have closed the issue prematurely. I have now updated the requirements.txt file.

**Comment by dhimmel** [comment]
> I have now updated the requirements.txt file.

Got it! I see https://github.com/sagepublishing/rejected_article_tracker_pkg/commit/ce3fbce99bdc4e7b75b9206ddb15566aabddc66a. Thanks for mentioning the issue in the commit `see: issues/4`. If you format this like `#4`, then GitHub will automatically show the commit on this issue.

CI is [now failing](https://github.com/sagepublishing/rejected_article_tracker_pkg/runs/2913467719) due to a different issue:

```python-traceback
  File "/home/runner/work/rejected_article_tracker_pkg/rejected_article_tracker_pkg/rejected_article_tracker/src/CrossRef.py", line 46, in search
    'mailto': os.environ['MY_EMAIL']
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MY_EMAIL'
```

Perhaps you need to set an email for testing?

**Comment by ad48** [comment]
Ah thanks! I had missed that. I've corrected this and github actions seem to now be working properly. 

Thanks for the tip about issue numbering. I will try to keep that in mind in future.

**Comment by dhimmel** [comment]
> I've corrected this and github actions seem to now be working properly.

Noting https://github.com/sagepublishing/rejected_article_tracker_pkg/commit/9a99b2dd33cbf117b05b5a800ca2de8209f31259, which [passed CI](https://github.com/sagepublishing/rejected_article_tracker_pkg/runs/2940801327)!
