### ISSUE TITLE
No recent releases on PyPI

### ISSUE THREAD

**Issue by dhimmel** [sagepublishing/rejected_article_tracker_pkg#5]
The most recent release is 1.5.0, which is missing 74 commits https://github.com/sagepublishing/rejected_article_tracker_pkg/compare/1.5.0...fc4f72de7b12c4acc6af597d61464ef7ed6e943b from the current main branch.

For my review of this software, I will install from the GitHub repo, but is it time to make a new release?

If it's helpful, my preferred way to release and upload  to PyPI these days is to use GitHub Actions, a project-scoped PyPI token, and setuptools_scm. Here are two pieces of code for an example:

1. https://github.com/related-sciences/nxontology/blob/970ee9a773b9bf907bb47afc705d40c8f0df5014/pyproject.toml#L1-L6
2. https://github.com/related-sciences/nxontology/blob/970ee9a773b9bf907bb47afc705d40c8f0df5014/.github/workflows/release.yaml

Then you can just make the release via GitHub releases and the distribution will get uploaded to PyPI automatically.

**Comment by danielskatz** [comment]
in https://github.com/openjournals/joss-reviews/issues/3348

**Comment by ad48** [comment]
@andyleanlibrary I think you set up using Github actions(?) Looks like one of my commits will have caused the issue so I will look into it, too.

**Comment by andyhailscode** [comment]
Hi @ad48, yep! It should create and push a release when tagged.

**Comment by dhimmel** [comment]
There is now a [version 1.5.5 release](https://pypi.org/project/rejected-article-tracker/1.5.5/) on PyPI. This version string is coming from https://github.com/sagepublishing/rejected_article_tracker_pkg/blob/9a99b2dd33cbf117b05b5a800ca2de8209f31259/setup.py#L8

One thing that caught my eye is that the [git tags](https://github.com/sagepublishing/rejected_article_tracker_pkg/releases) now use a calendar versioning scheme like `20210629a` and `20210624a`. Is there a reason to use a different versioning scheme for the git tags and the package? It's a bit confusing.

**Comment by andyhailscode** [comment]
Hi @dhimmel,

It's a good point. I have always opted to go for calendar versioning as it's more meaningful (and ironically more semantic!). Do you know if PyPI supports calendar verisoning or do we need to use semver? 

I agree we should align them.

**Comment by dhimmel** [comment]
I think PyPI will support any string, so you would definitely be able to switch to calendar verisoning everywhere.

https://calver.org/ lists some Python projects that use calendar versioning.

**Comment by andyhailscode** [comment]
@ad48 Can you change this in setup.py? Cheers :-)

**Comment by dhimmel** [comment]
BTW if you want to remove the version from setup.py and source it only from the git tag, you can use https://github.com/pypa/setuptools_scm. Otherwise, you have to remember to change setup.py before making the git tag in the future.

**Comment by andyhailscode** [comment]
@dhimmel that's super helpful! We should add this.

**Comment by dhimmel** [comment]
Closing this since there is a new release on PyPI.
