### ISSUE TITLE
Paper: mention the primary workflow of ScholarOne exports

### ISSUE THREAD

**Issue by dhimmel** [sagepublishing/rejected_article_tracker_pkg#6]
From the readme, it looks like this software package is primarily designed to lookup rejected submissions from a ScholarOne export via Crossref's metadata search. The article fields follow the ScholarOne format and are match the fields exported by ScholarOne.

However, the manuscript [10.21105.joss.03348.pdf](https://github.com/sagepublishing/rejected_article_tracker_pkg/files/6652059/10.21105.joss.03348.pdf) doesn't mention ScholarOne, which seems like a large omission, as this tool is most relevant to administrators of ScholarOne journals.

**Comment by danielskatz** [comment]
in https://github.com/openjournals/joss-reviews/issues/3348

**Comment by dhimmel** [comment]
c30b755619bf0e9517f848827911797de5e37275 added the following to the "Statement of need" section:

> The rejected article tracker is set up, by default, to accept data in the format exported by [ScholarOne](https://clarivate.com/webofsciencegroup/solutions/scholarone/), presently the most popular system for managing peer-review. However, the input data required is minimal, so data from any peer-review management system should be easily adapted for the tracker. Instructions are given in the Readme.md file of [the github repository](https://github.com/ad48/rejected_article_tracker_pkg).
