### ISSUE TITLE
FileNotFoundError: rejected_article_tracker/src/ML/small_models/lr_model

### ISSUE THREAD

**Issue by dhimmel** [sagepublishing/rejected_article_tracker_pkg#9]
I did `pip install rejected_article_tracker` in a fresh environment. Hit the following error on import:

```python-traceback
>>> from rejected_article_tracker import RejectedArticlesMatch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhimmel/miniconda3/envs/rejected-article-tracker/lib/python3.9/site-packages/rejected_article_tracker/__init__.py", line 22, in <module>
    shutil.copy(lr_model_path, dest_model_path)
  File "/home/dhimmel/miniconda3/envs/rejected-article-tracker/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/dhimmel/miniconda3/envs/rejected-article-tracker/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dhimmel/miniconda3/envs/rejected-article-tracker/lib/python3.9/site-packages/rejected_article_tracker/src/ML/small_models/lr_model'
```

I see the following lines intended to include this file/directory in the distribution:

https://github.com/sagepublishing/rejected_article_tracker_pkg/blob/94ab0918d965437b4919ab60206e7762c40b77e8/setup.py#L17-L18

_testing as part of https://github.com/openjournals/joss-reviews/issues/3348_

**Comment by dhimmel** [comment]
Noting that [`src/ML/small_models/lr_model`](https://github.com/sagepublishing/rejected_article_tracker_pkg/blob/94ab0918d965437b4919ab60206e7762c40b77e8/rejected_article_tracker/src/ML/small_models/lr_model) is a file.

Documentation at https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html.

**Comment by ad48** [comment]
Apologies! This issue came up a few weeks ago and I thought I had fixed it. Will sort it out.

**Comment by ad48** [comment]
I updated `Manifest.in` and this seems to have corrected the issue. I've reinstalled and run from scratch. All appears to be working. (Sorry, I forgot to include the issue number in the commit) https://github.com/sagepublishing/rejected_article_tracker_pkg/blob/main/MANIFEST.in

**Comment by dhimmel** [comment]
> I updated Manifest.in and this seems to have corrected the issue

Okay updated in https://github.com/sagepublishing/rejected_article_tracker_pkg/commit/591c0db717541e480bb5f37a07130badf1f34dd9. Let me know when a new version is released on [PyPI](https://pypi.org/project/rejected-article-tracker/) and I will test things again.

**Comment by ad48** [comment]
@dhimmel I think that's the latest version up there now. I've reinstalled from pypi and run the run_sample.py file which is working as expected.
